[package]
name = "uwuifier_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
xxhash-rust = { version = "*", features = ["xxh3"] }

[dev-dependencies]
criterion = "0.5.1"

# keep your code optimized ğŸ˜Šâ¤ï¸
[profile.release]
opt-level = 3
lto = true
strip = true
incremental = true